# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Urban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='text',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='mark',
            name='type',
            field=models.IntegerField(default=0, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
