# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urban', '0004_auto_20170830_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='text',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
