# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urban', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Female'), (2, 'Male')], default=0, verbose_name='Gender'),
        ),
    ]
